version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 635457412353.dkr.ecr.ap-northeast-1.amazonaws.com
      - echo Setting up environment variables...
      - REPO_URI=635457412353.dkr.ecr.ap-northeast-1.amazonaws.com/topson0205
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo Building Angular application...  # 新增
      - npm run build  # 新增：在这里生成 dist/ 目录
      - ls -la dist/   # 新增：确认 dist/ 目录已生成

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPO_URI:latest .
      - docker tag $REPO_URI:latest $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker images to ECR...
      - docker push $REPO_URI:latest
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"web","imageUri":"%s"}]' $REPO_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json  # 确认文件内容

artifacts:
  files:
    - imagedefinitions.json